### ISSUE TITLE
Feature Request: Custom path for models folder

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus#11]
Instead of having multiple copies of checkpoints, lora,s embeddings TI, I keep them in once central place on my fastest SSD drive (This will make Fooocus faster)  then I instruct A1111 and Comfyui to look there.

Request for custom path for checkpoints, Loras, and outputs in settings.json

I believe the file to edit is Fooocus-MoonRide/modules/path.py

Priority is not urgent, I could just hard code in path.py.  Only want to know if MoonRide is interested or has the time?

**Comment by MoonRide303** [comment]
@barepixels Simplest way to do it is by using OS features like links - this way you can have those models in single place, even on a different drive, yet make them all accessible to different applications on different drives expecting to have them in their own folder structure.

Most Linux users know this mechanisms, but many people using Windows don't know similar features are available on Windows, too. If you're Windows users, you can check out [mklink](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) documentation. Symlinks on Windows require admin rights, hardlinks and junctions work fine without it. If you're on Linux, you can check out [this guide](https://www.digitalocean.com/community/tutorials/workflow-symbolic-links) for symlinks.

As I find those OS features good solution for this use case, I won't be implementing settings for folders in Fooocus.

**Comment by MoonRide303** [comment]
Update: implemented ([fa61511](https://github.com/MoonRide303/Fooocus-MRE/commit/fa61511900baa642193bbe23c5967c866f81b86c)) - people having problems with links (discussed in #12) will have alternative solution.
