### ISSUE TITLE
Feature request: Store prompt in exif tag named 'comment' instead of 'prompt'

### ISSUE THREAD

**Issue by That-Dude** [MoonRide303/Fooocus#2]
Storing the prompt data in a tag called 'prompt' is logical but it's a non-standard tag and image viewers don't see it. At least not Photoshop, Macos-Preview or XnView.

If you store the prompt data in a tag called name 'comment' it's immediately available.

Given that were talking about 1 kilobyte of data, could you alter your code to store it in both tags  'prompt' AND 'comment' ?

![Screenshot 2023-08-16 at 17 39 26](https://github.com/MoonRide303/Fooocus/assets/6509533/419fb2b7-a625-4752-ae22-66ac263f02db)

**Comment by MoonRide303** [comment]
Good idea - I will look into it, but it might be a bit more complicated than simply changing key value from "prompt" to "comment" - I will test it with XnView. Properly implemented it should probably appear under "Image / Embedded Comment" (not "Extra / prompt" or "Extra / comment") in XnView, as in [IPTC samples](https://www.iptc.org/standards/photo-metadata/iptc-standard/).

**Comment by barepixels** [comment]
FYI metadata shows at this site also  
https://jimpl.com/

**Comment by That-Dude** [comment]
> @That-Dude fixed in [207712b6cad7601b311fb1e9e8de96622c94f08d](https://github.com/MoonRide303/Fooocus/commit/207712b6cad7601b311fb1e9e8de96622c94f08d) - please check it out, and close if working as intended (I tested on XnView).

Works great, thank you. 

It looks like your fork is going to become popular as they have closed off the request in favour of their own proprietary solution. I'm genuinely baffled by this 🤷🏼‍♂️

**Comment by MoonRide303** [comment]
Issues solved - closing it.

**Comment by That-Dude** [comment]
> @That-Dude Well @lllyasviel was kinda clear about his design choices for Fooocus:
> 
> ```
> 
> Learned from Stable Diffusion, the software is offline, open source, and free.
> 
> Learned from Midjourney, the manual tweaking is not needed, and users only need to focus on the prompts and images.
> 
> ```
> 
> and to be honest those are pretty good assumptions - I respect and like those. I also like the idea of integrated sampler he implemented. But we have to remember that Fooocus isn't (and won't be) direct competition for A1111 or ComfyUI, where users need to get knowledge about SD pipeline details to use them. It's about delivering simple tool with clean UI, able to efficiently generate high quality output. It's about allowing users to focus on prompting, and letting the tool to do the rest (as much as reasonably possible).
> 
> 
> 
> I maintain this fork mainly for my own use, cause I have some experience with prompting, and I know that tweaking some parameters like steps, CFG, or CLIP skip is often best and fastest way to refine given prompt into image into what you want - changing CFG and/or CLIP Skip values allows you to control generalisation, for that example (and optimal values might vary per model + seed + prompt combination, or even per your own personal artistic taste). But as an old geek and experienced prompter I am not really target group of Fooocus, so I just accepted it - and hence this fork. If anyone else finds it useful / helpful - that's not my primary goal, but it's nice to hear :).
> 
> 
> 
> I intend to stick to the same design rules that are behind vanilla Fooocus, but I want to look at them from a bit more experienced prompter perspective. Let's say vanilla Fooocus is designed for 10yo users, A1111 and ComfyUI are for adults, and my fork could be good choice for teenagers - allowing you to have a bit more control (via Advanced settings) in case you want it, but also remaining clean and simple by default.

I agree with the philosophy of a simple interface design that just works, its what's needed to popularise SDXL. Having extra features in the advanced tab is a great design choice. 

Your fork is what i would summarise as quality of life improvements for power users.

When A1111 gets its act together with SDXL I'll probably move over to that so i can access controlnet etc. But right now your fork is easily the best bet for creatives like me.
