### ISSUE TITLE
Expose more options in the GUI

### ISSUE THREAD

**Issue by That-Dude** [MoonRide303/Fooocus#6]
It would be useful to have a tickbox that exposes the CFG and sampler options on the front page. It great having this all hidden away but sometimes you want to experiment.

**Comment by MoonRide303** [comment]
@That-Dude I am not sure if I see the problem - when I enable Advanced mode in lower right corner I can see and change all the settings you've mentioned on the right, and then generate image with those settings - like that:
![image](https://github.com/MoonRide303/Fooocus/assets/130458190/a0a7c1d6-8e29-4048-b749-249f5045c796)

**Comment by That-Dude** [comment]
Oh gosh, when did they get added. I can't keep up with you! 😀

**Comment by MoonRide303** [comment]
I am glad you like it ^^. Issues seems solved, so I am closing it.
