### ISSUE TITLE
Print image meta data to screen for easy copy/paste

### ISSUE THREAD

**Issue by That-Dude** [MoonRide303/Fooocus#7]
I appreciate we now have this data in the PNG but having it printed to screen somewhere would also be useful, especially the seed and image dimensions. 

BTW if I'm saturating you with requests please just say!

**Comment by MoonRide303** [comment]
@That-Dude Basic information like seed and resolution are already there (selected resolution and seed is displayed in the basic UI), but some additional information (like full prompts) were indeed missing. I've just added (merged to moonride-main) dedicated tab for displaying metadata for generated images - it looks like that:
![image](https://github.com/MoonRide303/Fooocus/assets/130458190/fa16e083-1c10-4d0b-a695-44a4c24baa97)

**Comment by That-Dude** [comment]
Nice work! That more than meets my needs. I'm using your fork a lot today and the quality of life improvements are great.

If you wanted to get fancy you could de-code that JSON and present it in a more human readable format.

**Comment by MoonRide303** [comment]
Yeah, taking into account we already have human-readable format already available in log file (thanks to lllyasviel, [#160 in vanilla](https://github.com/lllyasviel/Fooocus/discussions/160)), I consider this issue as finished - closing.
