### ISSUE TITLE
Feature Request: Add scheduler selection to advanced tab

### ISSUE THREAD

**Issue by theelefant** [MoonRide303/Fooocus#9]
In ComfyUI, the sampler settings include an option to select the scheduler, giving users an added layer of control over image generation. It might be worthwhile to incorporate this feature into this repository as well.

**Comment by MoonRide303** [comment]
@theelefant Done ([c5900f1298163806f99f4a490eaca71050ef5d1d](https://github.com/MoonRide303/Fooocus/commit/c5900f1298163806f99f4a490eaca71050ef5d1d)), merged into moonride-main - I included those which worked well the integrated sampler.

Quick illustration (seed: 0, prompt: whatever, rest defaults) below:

karras:
![image](https://github.com/MoonRide303/Fooocus/assets/130458190/7521ac78-f392-4d44-8b33-b904dce63621)

exponential:
![image](https://github.com/MoonRide303/Fooocus/assets/130458190/96906aa6-3324-445f-b5a2-bf5f856b12ff)

simple:
![image](https://github.com/MoonRide303/Fooocus/assets/130458190/d654d513-3f3e-4aab-b7d1-1d17eee488c0)

ddim_uniform:
![image](https://github.com/MoonRide303/Fooocus/assets/130458190/867e6eef-2d7f-42da-a286-be6ad1a10cf8)
